= Tp2

image:https://img.shields.io/badge/vert.x-3.8.3-purple.svg[link="https://vertx.io"]

TP Cara Vertx

Contexte:
Pour ce Tp 2, on va essayer de communiquer les verticles Serveurs et les cuisiniers et les clients tous d'un seul coup, on aura un serveur qui va envoyer un message vers cuisinier, et que le cuisinier

```
Start of RestaurantLauncher
Start of Restaurant Verticle
Restaurant Verticle Deployed
[Cuisinier] - Start of Cuisinier Verticle
[Cuisinier] - Start of Cuisinier Verticle
[Serveur] - Start of Serveur Verticle
[Serveur] - Start of Serveur Verticle
End of RestaurantLauncher
[Serveur] consumer1 <- {"id":1,"clientStatus":0,"plat":"","commandeStatus":0}
Nombre de Clients dans le Restaurant:1
[Serveur] consumer1 <- {"id":2,"clientStatus":0,"plat":"","commandeStatus":0}
Nombre de Clients dans le Restaurant:2
```

== Question 1.ServeurVerticle (Envoyer message vers Cuisinier)

-   ajouter le code pour envoyer un message on utilisent la méthode send et getDeliveryOptions

== Question 2.CuisinierVerticle (Recevoir le message de Serveur)

-   Ajouter le code pour recevoir le message de serveur dans le verticle Cuisinier.
-   Modifier status de la commande.

== Question 3.CuisinierVerticle (Envoyer le message vers Serveur)

-   Ajouter le code pour envoyer le message vers serveur dans le verticle Cuisinier en changeant le status de la commande

== Question 4.ServeurVerticle (Recevoir le message de Cuisinier et envoyer le message vers Client)

-   Mettre en place la récéption des message du Cuisinier par le Serveur.
-   Modifier le status du clinet et de la commande.
-   Envoyer le message vers client.

== Help
* https://blog.invivoo.com/vert-x-basics-concurrence-et-scalabilite-avec-les-verticles/[Vert.x Verticles]
* https://www.mednikov.net/vertx-eventbus/[Vert.x EventBus]
* https://vertx.io/docs/vertx-core/java/#_asynchronous_counters[Counter]
* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


